language: asm
sudo: false
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/c64lib/travis-ci/master/install.sh)
script:
  - cpm common https://github.com/c64lib/common/archive/master.tar.gz
  - cpm chipset https://github.com/c64lib/chipset/archive/master.tar.gz 
  - ka -libdir cpm_modules text.asm
  - ka -libdir cpm_modules scroll1x1.asm
notifications:
  email:
    on_success: change
    on_failure: change
